-- D1 sqlite schema
CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
email TEXT UNIQUE NOT NULL,
password_hash TEXT NOT NULL,
display_name TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE events (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
title TEXT NOT NULL,
description TEXT,
quadrant INTEGER DEFAULT 0,
start_at DATETIME,
end_at DATETIME,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
